import assert from 'node:assert/strict';
import { SqliteDatabaseAdapter } from '../db/sqliteAdapter.ts';
import { ConversationRepository } from '../repositories/conversationRepository.ts';
import { pastLoopInstruction, traceConversationId, traceFields } from '../../src/shared/conversation.ts';
const db = new SqliteDatabaseAdapter(':memory:');
await db.execute('CREATE TABLE users (id TEXT PRIMARY KEY); CREATE TABLE loop_traces (id TEXT PRIMARY KEY, user_id TEXT, source_session_id TEXT, xp_awarded INTEGER DEFAULT 0); CREATE TABLE ledger (id TEXT PRIMARY KEY, points INTEGER);');
await db.execute("INSERT INTO users (id) VALUES ('a'), ('b'); INSERT INTO loop_traces VALUES ('draft','a','conv_a',0),('confirmed','a','conv_old',1),('other','b','conv_b',0); INSERT INTO ledger VALUES ('reward',10);");
const repo = new ConversationRepository(db);
const message = (id, text = 'หัวหน้าขอแก้งาน') => ({ id, role: 'user', text });
const save = (id, data = {}, owner = 'a') => repo.save(owner, id, { messages: [message('m1')], revision: 0, ...data });
const fails = async (fn, status) => assert.rejects(fn, e => e.status === status);
const first = await save('conv_a'); assert.equal(first.revision, 1);
assert.deepEqual((await new ConversationRepository(db).get('a', 'conv_a')).messages, [message('m1')], 'survives repository recreation');
assert.equal(await repo.get('b', 'conv_a'), null);
await fails(() => save('conv_a', {}, 'b'), 404);
await fails(() => save('foreign_link', { parentTraceId: 'other' }), 404);
assert.equal((await save('conv_a')).revision, 1, 'lost-response retry is idempotent');
await fails(() => save('conv_a', { messages: [message('m1'), message('m2')] }), 409);
await save('conv_a', { revision: 1, messages: [message('m1'), message('m2')] });
assert.equal((await repo.get('a', 'conv_a')).messages.length, 2);
await fails(() => save('dupe', { messages: [message('m1'), message('m1')] }), 400);
await fails(() => save('streaming', { messages: [{ ...message('m1'), isStreaming: true }] }), 400);
await fails(() => save('conv_old'), 409, 'confirmed source transcript frozen');
await save('followup', { parentTraceId: 'confirmed' });
await fails(() => repo.assertCanCreateTrace('a', 'followup'), 409);
await fails(() => repo.assertCanCreateTrace('b', 'followup'), 404);
await repo.assertCanCreateTrace('a', 'conv_a');
assert.deepEqual(await db.query('SELECT * FROM ledger'), [{id:'reward',points:10}], 'history and continuation never mutate rewards');
assert.deepEqual((await repo.list('a', 'confirmed')).map(c => c.id).sort(), ['followup']);
await fails(() => repo.list('b', 'confirmed'), 404);
await repo.remove('b', 'conv_a'); assert.ok(await repo.get('a', 'conv_a'), 'other owner cannot delete');
await repo.remove('a', 'conv_a'); assert.equal(await repo.get('a', 'conv_a'), null);
await fails(() => save('conv_a', { revision: 3 }), 410, 'stale tab cannot resurrect deletion');
assert.equal(traceConversationId({id:'guest_trc_conv_xyz'}), 'conv_xyz');
assert.deepEqual(traceFields({raw_data_json: '{"trigger":"เรื่องเดิม","emotionOrBody":"ยังไม่ได้สำรวจ"}'}), {trigger:'เรื่องเดิม'});
assert.match(pastLoopInstruction('ครั้งก่อนรู้สึกเศร้า'), /PAST/);
assert.match(pastLoopInstruction('ครั้งก่อนรู้สึกเศร้า'), /Do not assume old feelings/);
assert.equal(pastLoopInstruction({malicious:true}), '');
await db.close();
console.log('PASS: durable history, owner isolation, draft links, revisions, idempotency, immutable source, no continuation rewards, deletion tombstones, past context');
