import assert from 'node:assert/strict';
import { readFile, mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { stripTypeScriptTypes } from 'node:module';
import { SqliteDatabaseAdapter } from '../db/sqliteAdapter.ts';
import { emptyFutureJournal, reconcileFutureJournal } from '../../src/shared/futureSelf.ts';
const shared = new URL('../../src/shared/futureSelf.ts', import.meta.url).href;
const temporary = await mkdtemp(path.join(tmpdir(), 'future-self-test-'));
async function load(relative, from) {
  const source = (await readFile(new URL(relative, import.meta.url), 'utf8')).replace(from, shared);
  const target = path.join(temporary, path.basename(relative).replace('.ts', '.mjs'));
  await writeFile(target, stripTypeScriptTypes(source));
  return import(pathToFileURL(target).href);
}
const { FutureSelfRepository } = await load('../repositories/futureSelfRepository.ts', '../../src/shared/futureSelf.js');
const { FutureSelfStore } = await load('../../src/lib/futureSelfStore.ts', '../shared/futureSelf.js');
const db = new SqliteDatabaseAdapter(':memory:');
await db.execute("CREATE TABLE users (id TEXT PRIMARY KEY); INSERT INTO users VALUES ('a'), ('b'); CREATE TABLE ledger (points INTEGER); INSERT INTO ledger VALUES (15);");
const repo = new FutureSelfRepository(db);
const focus = (id = 'one') => ({ id, title: 'ค่อย ๆ บอกความต้องการ ' + id, outcome: '', cue: 'เมื่อยังไม่พร้อม', action: 'ขอเวลาคิดก่อน', obstacle: '', fallback: '' });
const entry = (id = 'e1') => ({ id, at: '2026-09-18T12:00:00.000Z', focus: 'บอกความต้องการ', action: 'ขอเวลาคิด', result: 'same', note: 'ยังไม่เห็นต่าง' });
const memory = () => { const values = new Map(); return { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value), values }; };
const remote = owner => (method, value) => method === 'GET' ? repo.get(owner) : repo.save(owner, value);
const fail = (fn, status) => assert.rejects(fn, e => e.status === status);
const settle = store => store.sync();
const initial = await repo.get('a'); assert.equal(initial.revision, 0);
const first = await repo.save('a', { revision: 0, journal: { focus: focus(), entries: [entry()] } });
assert.equal(first.revision, 1);
assert.equal((await repo.save('a', { revision: 0, journal: first.journal })).revision, 1, 'lost response retry does not duplicate');
assert.deepEqual((await repo.get('b')).journal, emptyFutureJournal(), 'account reads isolated');
await fail(() => repo.save('a', { revision: 0, journal: { focus: focus('stale'), entries: [entry()] } }), 409);
await fail(() => repo.save('a', { revision: 1, journal: { focus: focus(), entries: [] } }), 409);
await fail(() => repo.save('a', { revision: 1, journal: { focus: focus(), entries: [entry(), entry()] } }), 400);
await fail(() => repo.save('a', { revision: 1, journal: { focus: focus(), entries: [{...entry(), result:'invented'}] } }), 400);
await fail(() => repo.save('a', { revision: 1, journal: { focus: focus(), entries: [{...entry(), note:'edited old entry'}] } }), 409);
const storageA = memory(), storageB = memory();
const a = new FutureSelfStore('a', storageA, remote('a'));
const b = new FutureSelfStore('a', storageB, remote('a'));
await a.sync(); await b.sync();
assert.equal(b.getSnapshot().journal.entries.length, 1, 'second device restores same account');
a.commit({ focus: focus(), entries: [entry('from-a'), ...a.getSnapshot().journal.entries] });
await settle(a);
b.commit({ focus: focus(), entries: [entry('from-b'), ...b.getSnapshot().journal.entries] });
await settle(b);
assert.deepEqual((await repo.get('a')).journal.entries.map(e => e.id).sort(), ['e1','from-a','from-b'], 'concurrent reflections merged');
await a.sync(); await b.sync();
a.commit({ ...a.getSnapshot().journal, focus: focus('plan-a') }); await settle(a);
b.commit({ ...b.getSnapshot().journal, focus: focus('plan-b') }); await settle(b);
assert.equal(b.getSnapshot().status, 'conflict');
assert.equal((await repo.get('a')).journal.focus.id, 'plan-a', 'conflicting local focus cannot overwrite remote');
const reopenedConflict = new FutureSelfStore('a', storageB, remote('a')); await reopenedConflict.sync();
assert.equal(reopenedConflict.getSnapshot().status, 'conflict', 'conflict survives reload');
reopenedConflict.resolveConflict('account'); await settle(reopenedConflict);
assert.equal(reopenedConflict.getSnapshot().journal.focus.id, 'plan-a');
assert.equal(reopenedConflict.getSnapshot().journal.entries.length, 3);
// The other choice explicitly commits the local plan.
await b.sync(); b.resolveConflict('local'); await settle(b);
assert.equal((await repo.get('a')).journal.focus.id, 'plan-b');
// Offline journal is stored before the first network request and survives reload.
let offline = true;
const offlineStorage = memory();
const offlineTransport = async (method, value) => { if (offline) throw new Error('offline'); return remote('a')(method, value); };
const off = new FutureSelfStore('a', offlineStorage, offlineTransport); await off.sync();
assert.equal(off.getSnapshot().status, 'offline');
off.commit({ focus: null, entries: [entry('offline')] }); await settle(off);
const resumed = new FutureSelfStore('a', offlineStorage, offlineTransport);
assert.equal(resumed.getSnapshot().journal.entries[0].id, 'offline');
offline = false; await resumed.sync();
assert.equal(resumed.getSnapshot().status, 'synced');
assert.equal(resumed.getSnapshot().journal.focus.id, 'plan-b', 'offline reflection does not clear the account plan');
assert.equal((await repo.get('a')).journal.entries.length, 4);
// A lost PUT response is recovered without another entry or revision.
let loseResponse = true;
const lost = new FutureSelfStore('a', memory(), async (method, value) => { const result = await remote('a')(method, value); if (method === 'PUT' && loseResponse) { loseResponse = false; throw new Error('response lost'); } return result; });
await lost.sync(); lost.commit({ ...lost.getSnapshot().journal, entries: [entry('lost'), ...lost.getSnapshot().journal.entries] }); await settle(lost);
const lostRevision = (await repo.get('a')).revision;
await lost.sync(); assert.equal((await repo.get('a')).revision, lostRevision);
assert.equal(lost.getSnapshot().status, 'synced');
// Preserve changes made while an older save is still in flight.
let releasePut, putStarted;
const started = new Promise(resolve => { putStarted = resolve; });
const gate = new Promise(resolve => { releasePut = resolve; });
let block = true;
const rapid = new FutureSelfStore('a', memory(), async (method, value) => { if (method === 'PUT' && block) { block = false; putStarted(); await gate; } return remote('a')(method, value); });
await rapid.sync(); rapid.commit({ ...rapid.getSnapshot().journal, entries: [entry('rapid-1'), ...rapid.getSnapshot().journal.entries] });
await started;
rapid.commit({ ...rapid.getSnapshot().journal, entries: [entry('rapid-2'), ...rapid.getSnapshot().journal.entries] });
releasePut(); await settle(rapid);
assert.equal((await repo.get('a')).journal.entries.filter(e => e.id.startsWith('rapid')).length, 2);
// Old account-local data imports once; guest data requires an explicit action.
const migrationStorage = memory();
migrationStorage.setItem('deung_sati_future_practice_v1_b', JSON.stringify({ focus: focus('legacy'), entries: [entry('legacy')] }));
migrationStorage.setItem('deung_sati_future_practice_v1_guest', JSON.stringify({ focus: focus('guest'), entries: [entry('guest')] }));
const migrated = new FutureSelfStore('b', migrationStorage, remote('b')); await migrated.sync();
assert.deepEqual((await repo.get('b')).journal.entries.map(e => e.id), ['legacy']);
assert.ok(migrated.guestImport()); assert.equal(migrated.importGuest(), true); await settle(migrated);
assert.equal((await repo.get('b')).journal.focus.id, 'legacy');
assert.equal((await repo.get('b')).journal.entries.length, 2);
assert.equal(migrated.guestImport(), null);
assert.ok(migrationStorage.getItem('deung_sati_future_practice_v1_guest'), 'guest source copy retained');
assert.ok(migrationStorage.getItem('deung_sati_future_practice_v1_b'), 'legacy account backup retained');
assert.equal((await repo.get('a')).journal.entries.some(e => e.id === 'guest'), false, 'import affects only selected account');
// Wrong-owner responses are never displayed or stored under the current account.
const wrong = new FutureSelfStore('b', memory(), remote('a')); await wrong.sync();
assert.deepEqual(wrong.getSnapshot().journal, emptyFutureJournal());
assert.equal(wrong.getSnapshot().status, 'offline');
const guest = new FutureSelfStore('guest', memory());
assert.equal(guest.commit({ focus: focus('guest-only'), entries: [] }), true);
assert.equal(guest.getSnapshot().status, 'local');
const corrupt = memory(); corrupt.setItem('deung_sati_future_practice_v1_a', '{broken');
const damaged = new FutureSelfStore('a', corrupt, remote('a')); await damaged.sync();
assert.equal(damaged.commit(emptyFutureJournal()), false); assert.equal(corrupt.getItem('deung_sati_future_practice_v1_a'), '{broken');
const full = new FutureSelfStore('guest', {getItem:()=>null,setItem:()=>{throw new Error('full')}});
assert.equal(full.commit({focus:focus(),entries:[]}), false);
assert.deepEqual(await db.query('SELECT * FROM ledger'), [{points:15}], 'Future Self never grants loop rewards');
assert.equal(reconcileFutureJournal(emptyFutureJournal(), emptyFutureJournal(), {focus:focus(),entries:[]}).conflict, false);
await db.close();
await rm(temporary, { recursive: true });
console.log('PASS Future Self: account isolation, two-device merge/conflict, offline reload, in-flight edits, idempotent retry, legacy import, explicit guest import, wrong-owner response, storage failure, unchanged rewards');
