import assert from 'node:assert/strict';
import { test } from 'node:test';
import { SqliteDatabaseAdapter } from '../db/sqliteAdapter.js';
import { runMigrations } from '../db/migrator.js';
import { AuthService } from '../services/authService.js';
import { CompanionRepository } from '../repositories/companionRepository.js';
import { LoopRepository } from '../repositories/loopRepository.js';
import { RoomRepository } from '../repositories/roomRepository.js';
const dna = { primary_pink_shade:'soft_sakura',secondary_color:'#8BD3DD',gill_type:'triple_feather',cheek_feeler_type:'soft_droplet',head_light_type:'lantern',head_light_tip:'warm_glow',tail_type:'flowing_fin',body_pattern:'ripples',movement_personality:'calm_float',safe_space_theme:'misty_moss' };
test('saved loops deliver durable, idempotent growth; hatch DNA stays frozen; bond and weather persist', async () => {
 const db = new SqliteDatabaseAdapter(); await runMigrations(db);
 const auth=new AuthService(db), pets=new CompanionRepository(db), loops=new LoopRepository(db), room=new RoomRepository(db);
 const user=(await auth.register('Room test','room@example.test','Password123!')).user.id;
 const other=(await auth.register('Other','other@example.test','Password123!')).user.id;
 await pets.createCompanion(user,42,dna,'เพื่อน');
 const save=async (n:number, extra:any={}) => {
  const trace=await loops.createTrace(user,{title:`เหตุการณ์ ${n}`,category:'emotional',trigger:`เพื่อนไม่ตอบข้อความครั้งที่ ${n}`,emotionOrBody:'กังวล แน่นหน้าอก',automaticStory:'คิดว่าเพื่อนไม่ชอบเรา',facts:'ส่งข้อความไปแล้วหนึ่งชั่วโมงยังไม่ตอบ',newChoice:'รอและไปทำสิ่งที่ตั้งใจไว้',insights:'ยังไม่รู้เหตุผลที่แท้จริง'} as any);
  const data={loopTraceId:trace.id,idempotencyKey:`room-test-${n}`,skills:{emotional_awareness:1,cognitive_clarity:1},...extra};
  return {result:await loops.confirmGrowthEvent(user,data),data};
 };
 const first=await save(1); assert.equal(first.result.reward.xp,15);
 const replay=await loops.confirmGrowthEvent(user,first.data); assert.equal(replay.reward.xp,0);
 assert.equal((await room.state(user)).events.length,1);
 const event=(await room.state(user)).events[0]; assert.equal(event.payload.progress,1);
 assert.equal((await new RoomRepository(db).state(user)).events[0].id,event.id);
 await room.acknowledge(other,event.id); assert.equal((await room.state(user)).events.length,1);
 await room.acknowledge(user,event.id); assert.equal((await room.state(user)).events.length,0);
 assert.equal((await room.state(user)).weather,'mist');
 await room.weather(user,'snow'); assert.equal((await new RoomRepository(db).state(user)).weather,'snow');
 await save(90,{isReview:true}); await save(91,{isCrisis:true});
 assert.equal((await room.state(user)).events.length,0);
 assert.equal(await loops.getCompletedLoopCount(user),1);
 for(let n=2;n<=20;n++) await save(n);
 const hatched=await pets.findByUserId(user); assert.equal(hatched?.stage,1); assert.ok(hatched?.snapshot);
 const before=JSON.stringify(hatched!.snapshot!.dna_json);
 await save(21); assert.equal(JSON.stringify((await pets.findByUserId(user))!.snapshot!.dna_json),before);
 assert.equal((await room.state(user)).events.filter(e=>e.payload.hatched).length,1);
 const rewards=await db.query<any>("SELECT * FROM currency_transactions WHERE user_id=$1 AND event_type='growth_event_reward' AND currency='xp'",[user]); assert.equal(rewards.length,5);
 await room.interact(user,'click-1'); await room.interact(user,'click-1'); await room.interact(user,'click-2');
 assert.equal((await room.state(user)).bond,1);
 await db.execute('UPDATE companion_rooms SET last_bond_at = NULL WHERE user_id=$1',[user]); await room.interact(user,'click-3');
 await db.execute('UPDATE companion_rooms SET last_bond_at = NULL WHERE user_id=$1',[user]); await room.interact(user,'click-4');
 const unlocked=(await room.state(user)).events.find(e=>e.payload.unlocks?.includes('scratch')); assert.ok(unlocked);
 await room.acknowledge(user,unlocked!.id); assert.ok(!(await room.state(user)).events.some(e=>e.id===unlocked!.id));
 assert.equal((await room.state(user)).bond,3);
 // Inject failure at the final event write: rewards and the loop confirmation must roll back together.
 const original = db.execute.bind(db);
 db.execute = async (sql, params) => { if(sql.startsWith('INSERT INTO companion_room_events')) throw new Error('injected queue failure'); return original(sql,params); };
 const countBefore = await loops.getCompletedLoopCount(user);
 await assert.rejects(save(99), /injected queue failure/);
 db.execute = original;
 assert.equal(await loops.getCompletedLoopCount(user),countBefore);
 await db.close();
});
